// @ts-check

// 这在 Node.js 中运行 - 不要在这里使用客户端代码（浏览器 API，JSX...）

/**
 * 创建一个侧边栏可以让你：
 - 创建一个有序的文档组
 - 为该组的每个文档渲染一个侧边栏
 - 提供上下文导航

 侧边栏可以从文件系统生成，或者在这里显式定义。

 你可以创建任意数量的侧边栏。

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 默认情况下，Docusaurus 从文档文件夹结构生成侧边栏
  // 这行代码的意思是自动生成一个侧边栏，dirName: '.' 表示从当前目录开始生成
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // 但你可以手动创建一个侧边栏
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
